[app]

# App name + package
title           = WBS Berlin
package.name    = wbsberlin
package.domain  = de.alaa.wbs

# Source
source.dir       = .
source.include_exts = py,png,jpg,kv,atlas,json,ttf

# Version
version = 1.0.0

# Dependencies — only what's needed
requirements = python3==3.11.6,kivy==2.2.1,httpx==0.27.2,beautifulsoup4==4.12.3,lxml==5.3.0,certifi,chardet,h11,h2,httpcore

# Orientation + UI
orientation = portrait
fullscreen   = 0
android.window_soft_input_mode = adjustResize

# Icons (generated by GitHub Actions from icon.png)
icon.filename     = %(source.dir)s/icon.png
presplash.filename = %(source.dir)s/presplash.png

# Android config
android.api     = 34
android.minapi  = 24
android.ndk     = 25b
android.ndk_api = 24
android.archs   = arm64-v8a

# Permissions
android.permissions = INTERNET,ACCESS_NETWORK_STATE,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE,VIBRATE

# Gradle
android.gradle_dependencies = com.android.support:support-compat:28.0.0
android.enable_androidx     = True

# Release
android.release_artifact  = apk
android.debug_artifact    = apk
android.allow_backup      = True

[buildozer]
log_level = 2
warn_on_root = 1
